Generalized-Core-Counter: src/StateHandlers.h File Reference
StateHandlers.h File Reference
#include "StateMachine.h"
Functions
void handleConnectingState ()
CONNECTING_STATE: establish cloud connection using a phased, non-blocking state machine.
void handleCountingMode ()
Handle sensor events in COUNTING mode.
void handleErrorState ()
void handleFirmwareUpdateState ()
void handleIdleState ()
void handleOccupancyMode ()
Handle sensor events in OCCUPANCY mode.
void handleReportingState ()
void handleSleepingState ()
SLEEPING_STATE: deep sleep between reporting intervals.
void updateOccupancyState ()
Update occupancy state based on debounce timeout.
Function Documentation
handleConnectingState()
void handleConnectingState ()
CONNECTING_STATE: establish cloud connection using a phased, non-blocking state machine.
Uses an internal ConnectPhase enum to break connection into small steps that each complete within a single loop() iteration:
CONN_PHASE_START: log signal strength and request Particle.connect().
CONN_PHASE_WAIT_CLOUD: poll Particle.connected() up to connectAttemptBudgetSec (from sysStatus / Ledger), raising alert 31 on timeout.
CONN_PHASE_LOAD_CONFIG: load configuration from cloud ledgers and raise alert 41 on failure.
CONN_PHASE_PUBLISH_LEDGER: optionally publish device-data to the ledger (skipped when entered from REPORTING_STATE to avoid clobbering hourlyCount), log queue depth, and transition to FIRMWARE_UPDATE_STATE when updates are pending or back to IDLE_STATE. Connection duration is tracked in sysStatus so budgets and field behaviour can be analysed from device-status data.
Definition at line 733 of file StateHandlers.cpp.
References connectedStartMs, current, FIRMWARE_UPDATE_STATE, firstConnectionObserved, firstConnectionQueueDrainedLogged, IDLE_STATE, Cloud::instance(), Cloud::loadConfigurationFromCloud(), maxConnectAttemptMs, measure, oldState, publishDiagnosticSafe(), publishStateTransition(), REPORTING_STATE, SLEEPING_STATE, state, and sysStatus.
Referenced by loop().
handleCountingMode()
void handleCountingMode ()
Handle sensor events in COUNTING mode.
In counting mode, each sensor detection increments counters. Counts are tracked hourly and daily. Used for: traffic counting, people counting, event tracking
Definition at line 1049 of file StateHandlers.cpp.
References BLUE_LED, countSignalTimer, current, SensorManager::instance(), and loop().
Referenced by loop().
handleErrorState()
void handleErrorState ()
Definition at line 976 of file StateHandlers.cpp.
References ab1805, CONNECTED, current, IDLE_STATE, oldState, publishStateTransition(), resetWait, state, and sysStatus.
Referenced by loop().
handleFirmwareUpdateState()
void handleFirmwareUpdateState ()
Definition at line 838 of file StateHandlers.cpp.
References BUTTON_PIN, IDLE_STATE, Cloud::instance(), Cloud::loadConfigurationFromCloud(), oldState, publishStateTransition(), SLEEPING_STATE, and state.
Referenced by loop().
handleIdleState()
void handleIdleState ()
Definition at line 61 of file StateHandlers.cpp.
References CONNECTED, connectedStartMs, countSignalTimer, current, firstConnectionObserved, firstConnectionQueueDrainedLogged, SensorManager::instance(), isWithinOpenHours(), measure, oldState, publishStateTransition(), REPORTING_STATE, SCHEDULED, sensorDetect, SLEEPING_STATE, state, and sysStatus.
Referenced by loop().
handleOccupancyMode()
void handleOccupancyMode ()
Handle sensor events in OCCUPANCY mode.
In occupancy mode, first detection marks space as "occupied". Space remains occupied until debounce timeout expires without new detections. Tracks total occupied time for reporting. Used for: room occupancy, parking space detection, resource availability
Definition at line 1083 of file StateHandlers.cpp.
References BLUE_LED, current, SensorManager::instance(), loop(), sysStatus, and updateOccupancyState().
Referenced by loop().
handleReportingState()
void handleReportingState ()
Definition at line 621 of file StateHandlers.cpp.
References CONNECTING_STATE, COUNTING, current, dailyCleanup(), IDLE_STATE, measure, oldState, publishData(), publishStateTransition(), state, suppressAlert40ThisSession, and sysStatus.
Referenced by loop().
handleSleepingState()
void handleSleepingState ()
SLEEPING_STATE: deep sleep between reporting intervals.
Performs a non-blocking, phased disconnect before entering Device OS sleep modes. While connected (or with the radio still on) it gates sleep on the publish queue being in a sleep-safe state. The disconnect sequence uses an internal DisconnectPhase state machine to:
Request cloud disconnect and wait up to cloudDisconnectBudgetSec (from sysStatus / Ledger).
Power down the modem (Cellular/WiFi) and wait up to modemOffBudgetSec. If either budget is exceeded, alert 15 is raised and control transfers to ERROR_STATE so the error supervisor can decide on recovery. Once offline, the handler selects HIBERNATE or ULTRA_LOW_POWER based on opening hours and validates that long night sleeps are honoured.
Definition at line 232 of file StateHandlers.cpp.
References ab1805, BLUE_LED, BUTTON_PIN, config, CONNECTED, CONNECTING_STATE, conv, COUNTING, countSignalTimer, current, ERROR_STATE, hibernateDisabledForSession, IDLE_STATE, SensorManager::initializeFromConfig(), SensorManager::instance(), intPin, isWithinOpenHours(), OCCUPANCY, oldState, SensorManager::onEnterSleep(), SensorManager::onExitSleep(), publishStateTransition(), REPORTING_STATE, secondsUntilNextOpen(), sensorDetect, SLEEPING_STATE, state, sysStatus, userSwitchDetected, and wakeBoundary.
Referenced by loop().
updateOccupancyState()
void updateOccupancyState ()
Update occupancy state based on debounce timeout.
If space is occupied and debounce timeout has expired without new sensor events, mark space as unoccupied. Accumulates total occupied time for daily reporting.
Definition at line 1116 of file StateHandlers.cpp.
References BLUE_LED, current, and sysStatus.
Referenced by handleOccupancyMode().