Generalized-Core-Counter: src/state/State_Sleep.cpp File Reference
State_Sleep.cpp File Reference
#include "state/State_Common.h"
#include "Config.h"
#include "Cloud.h"
#include "LocalTimeRK.h"
#include "MyPersistentData.h"
#include "PublishQueuePosixRK.h"
#include "SensorManager.h"
#include "device_pinout.h"
#include "SensorDefinitions.h"
#include "AB1805_RK.h"
Functions
void handleSleepingState ()
SLEEPING_STATE: deep sleep between reporting intervals.
Function Documentation
handleSleepingState()
void handleSleepingState ()
SLEEPING_STATE: deep sleep between reporting intervals.
...
Definition at line 20 of file State_Sleep.cpp.
References ab1805, BLUE_LED, BUTTON_PIN, config, CONNECTED, CONNECTING_STATE, conv, COUNTING, countSignalTimer, current, ensureSensorEnabled(), ERROR_STATE, hibernateDisabledForSession, IDLE_STATE, SensorManager::initializeFromConfig(), SensorManager::instance(), intPin, isRadioPoweredOn(), isWithinOpenHours(), OCCUPANCY, oldState, SensorManager::onEnterSleep(), SensorManager::onExitSleep(), publishStateTransition(), REPORTING_STATE, requestFullDisconnectAndRadioOff(), secondsUntilNextOpen(), sensorDetect, SLEEPING_STATE, state, sysStatus, userSwitchDetected, and wakeBoundary.
Referenced by loop().