Generalized-Core-Counter: Particle_Functions Class Reference
Particle_Functions Class Reference
This class is a singleton; you do not create one as a global, on the stack, or with new.
#include <Particle_Functions.h>
Public Member Functions
void setup ()
Perform setup operations; call this from global application setup().
Static Public Member Functions
static Particle_Functions & instance ()
Gets the singleton instance of this class, allocating it if necessary.
Protected Member Functions
Particle_Functions & operator= (const Particle_Functions &)=delete
This class is a singleton and cannot be copied.
Particle_Functions ()
The constructor is protected because the class is a singleton.
Particle_Functions (const Particle_Functions &)=delete
This class is a singleton and cannot be copied.
virtual ~Particle_Functions ()
The destructor is protected because the class is a singleton and cannot be deleted.
Static Protected Attributes
static Particle_Functions * _instance
Singleton instance of this class.
Detailed Description
This class is a singleton; you do not create one as a global, on the stack, or with new.
From global application setup you must call: Particle_Functions::instance().setup();
Definition at line 21 of file Particle_Functions.h.
Constructor & Destructor Documentation
Particle_Functions() [1/2]
Particle_Functions::Particle_Functions () protected
The constructor is protected because the class is a singleton.
Use Particle_Functions::instance() to instantiate the singleton.
Definition at line 50 of file Particle_Functions.cpp.
Referenced by instance(), operator=(), and Particle_Functions().
~Particle_Functions()
Particle_Functions::~Particle_Functions () protected virtual
The destructor is protected because the class is a singleton and cannot be deleted.
Definition at line 52 of file Particle_Functions.cpp.
Particle_Functions() [2/2]
Particle_Functions::Particle_Functions (const Particle_Functions &) protected delete
This class is a singleton and cannot be copied.
References Particle_Functions().
Member Function Documentation
instance()
Particle_Functions & Particle_Functions::instance () static
Gets the singleton instance of this class, allocating it if necessary.
Use Particle_Functions::instance() to instantiate the singleton.
Definition at line 43 of file Particle_Functions.cpp.
References _instance, and Particle_Functions().
Referenced by setup().
operator=()
Particle_Functions & Particle_Functions::operator= (const Particle_Functions &) protected delete
This class is a singleton and cannot be copied.
References Particle_Functions().
setup()
void Particle_Functions::setup ()
Perform setup operations; call this from global application setup().
You typically use Particle_Functions::instance().setup();
Definition at line 54 of file Particle_Functions.cpp.
Referenced by setup().
Member Data Documentation
_instance
Particle_Functions * Particle_Functions::_instance static protected
Singleton instance of this class.
The object pointer to this class is stored here. It's NULL at system boot.
Definition at line 65 of file Particle_Functions.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/Particle_Functions.h
src/Particle_Functions.cpp